"""
Chapter 27: Shortest Vector in a Lattice
=========================================
Vazirani Ch. 27: Given a lattice L defined by a basis b_1,...,b_n in R^n,
find the shortest non-zero vector (SVP).

Implements:
1. Euclid's algorithm for 1D lattices (GCD = shortest vector)
2. Gauss' algorithm for 2D lattices
3. Gram-Schmidt orthogonalization and orthogonality defect
4. Lower bounding OPT using Gram-Schmidt
5. Extension to n dimensions via successive minima
6. The dual lattice and its algorithmic use
7. Basis reduction (simple n-dimensional)
"""

from typing import List, Tuple, Optional
import math


# ---------------------------------------------------------------------------
# Helper: pure-Python vector arithmetic
# ---------------------------------------------------------------------------

def vec_add(a: List[float], b: List[float]) -> List[float]:
    """Add two vectors."""
    return [a[i] + b[i] for i in range(len(a))]


def vec_sub(a: List[float], b: List[float]) -> List[float]:
    """Subtract vector b from a."""
    return [a[i] - b[i] for i in range(len(a))]


def vec_scale(a: List[float], s: float) -> List[float]:
    """Scale vector a by scalar s."""
    return [a[i] * s for i in range(len(a))]


def vec_dot(a: List[float], b: List[float]) -> float:
    """Dot product of two vectors."""
    return sum(a[i] * b[i] for i in range(len(a)))


def vec_norm(a: List[float]) -> float:
    """Euclidean norm of a vector."""
    return math.sqrt(vec_dot(a, a))


def vec_is_zero(a: List[float], tol: float = 1e-10) -> bool:
    """Check if a vector is (approximately) zero."""
    return vec_norm(a) < tol


def mat_rows(basis: List[List[float]]) -> List[List[float]]:
    """Return the rows of a basis matrix (basis is already rows)."""
    return [list(row) for row in basis]


# ---------------------------------------------------------------------------
# 1. Euclid's algorithm for 1D lattices
# ---------------------------------------------------------------------------

def euclid_gcd(a: int, b: int) -> int:
    """
    Euclid's algorithm: finds GCD(a, b).

    In a 1D lattice L = {n * a : n in Z}, the shortest non-zero vector
    has length |a|.  For a lattice spanned by a and b, the shortest vector
    is gcd(a, b).

    Vazirani Section 27.1: Euclid's algorithm computes the GCD, which is
    the shortest non-zero vector in the lattice generated by two integers.

    Returns:
        GCD of a and b (the shortest vector length in the lattice).
    """
    a, b = abs(a), abs(b)
    while b:
        a, b = b, a % b
    return a


# ---------------------------------------------------------------------------
# 2. Gauss' 2D algorithm
# ---------------------------------------------------------------------------

def gauss_2d(b1: List[float], b2: List[float]) -> List[float]:
    """
    Gauss' algorithm for 2D lattice: finds the shortest non-zero vector.

    Given two linearly independent vectors b1, b2 in R^2, repeatedly
    subtract the shorter from the longer, then swap, until convergence.

    Vazirani Section 27.2: Gauss' algorithm finds the shortest vector
    in a 2D lattice in polynomial time.  It is analogous to Euclid's
    algorithm but in 2D.

    The key insight: if |b1| < |b2|, replace b2 with b2 - round(<b2,b1>/<b1,b1>) * b1,
    then swap so the shorter vector is first.  Repeat until |b2| >= |b1|.

    Returns:
        The shortest non-zero lattice vector as a list of 2 floats.
    """
    b1, b2 = list(b1), list(b2)

    while True:
        # Ensure b1 is the shorter vector
        if vec_norm(b1) > vec_norm(b2):
            b1, b2 = b2, b1

        # Project b2 onto b1 and subtract
        dot_11 = vec_dot(b1, b1)
        if dot_11 < 1e-15:
            # b1 is (approximately) zero -- shouldn't happen for valid input
            break

        # Gauss' step: b2 <- b2 - round(<b2, b1> / <b1, b1>) * b1
        coeff = vec_dot(b2, b1) / dot_11
        rounded = round(coeff)
        b2 = vec_sub(b2, vec_scale(b1, rounded))

        # Check convergence: if |b2| >= |b1|, we are done
        if vec_norm(b2) >= vec_norm(b1):
            break

    return b1


# ---------------------------------------------------------------------------
# 3. Gram-Schmidt orthogonalization
# ---------------------------------------------------------------------------

def gram_schmidt(basis: List[List[float]]) -> Tuple[List[List[float]], List[List[float]]]:
    """
    Gram-Schmidt orthogonalization of a basis.

    Given basis b_1,...,b_n, compute the orthogonal basis b*_1,...,b*_n
    such that b*_i is the component of b_i orthogonal to span(b_1,...,b_{i-1}).

    Also returns the Gram-Schmidt coefficients mu_{i,j} = <b_i, b*_j> / <b*_j, b*_j>.

    Vazirani Section 27.3: Gram-Schmidt orthogonalization.  The key property
    is that |b*_i| <= |b_i| for all i, and the orthogonality defect
    prod_i |b_i| / prod_i |b*_i| measures how far the basis is from orthogonal.

    Returns:
        Tuple of (orthogonal_basis, coefficients) where:
        - orthogonal_basis: list of orthogonal vectors b*_1,...,b*_n
        - coefficients: list of lists mu where mu[i][j] for j < i are the
          Gram-Schmidt coefficients
    """
    n = len(basis)
    ortho = [list(basis[i]) for i in range(n)]
    mu = [[0.0] * n for _ in range(n)]

    for i in range(n):
        for j in range(i):
            dot_jj = vec_dot(ortho[j], ortho[j])
            if dot_jj > 1e-15:
                mu[i][j] = vec_dot(basis[i], ortho[j]) / dot_jj
            else:
                mu[i][j] = 0.0
            ortho[i] = vec_sub(ortho[i], vec_scale(ortho[j], mu[i][j]))

    return ortho, mu


def orthogonality_defect(basis: List[List[float]]) -> float:
    """
    Compute the orthogonality defect of a basis.

    The defect is prod(|b_i|) / prod(|b*_i|), where b*_i are the
    Gram-Schmidt orthogonal vectors.  A value of 1.0 means the basis
    is perfectly orthogonal.

    Vazirani Section 27.3: The orthogonality defect bounds how much
    shorter the Gram-Schmidt vectors are compared to the original basis.
    """
    ortho, _ = gram_schmidt(basis)
    num = 1.0
    den = 1.0
    for i in range(len(basis)):
        num *= vec_norm(basis[i])
        den *= vec_norm(ortho[i])
    if den < 1e-15:
        return float('inf')
    return num / den


# ---------------------------------------------------------------------------
# 4. Lower bound on OPT using Gram-Schmidt
# ---------------------------------------------------------------------------

def lower_bound_svp(basis: List[List[float]]) -> float:
    """
    Lower bound on the shortest vector length using Gram-Schmidt.

    Vazirani Section 27.4: For any lattice L with basis B,
    the shortest non-zero vector length OPT satisfies:
        OPT >= min_i |b*_i|
    where b*_i are the Gram-Schmidt orthogonal vectors.

    This is because any lattice vector v = sum c_i b_i has
    |v| >= |component in direction of b*_i| >= min_j |b*_j| for
    some direction.

    Returns:
        Lower bound on the shortest vector length.
    """
    ortho, _ = gram_schmidt(basis)
    min_norm = float('inf')
    for v in ortho:
        n = vec_norm(v)
        if n > 1e-15:
            min_norm = min(min_norm, n)
    return min_norm if min_norm < float('inf') else 0.0


# ---------------------------------------------------------------------------
# 5. Dual lattice
# ---------------------------------------------------------------------------

def dual_basis(basis: List[List[float]]) -> List[List[float]]:
    """
    Compute the dual basis b^1,...,b^n of a given basis b_1,...,b_n.

    The dual basis satisfies <b_i, b^j> = delta_{i,j} (Kronecker delta).

    Vazirani Section 27.6: The dual lattice L* = {x in R^n : <x, v> in Z for all v in L}.
    The dual basis is computed by solving B^T B^{-1}, or equivalently by
    Gram-Schmidt and back-substitution.

    For a 2D basis, we use the explicit formula:
        b^1 = (b_2_perp) / <b_1, b_2_perp>
        b^2 = (b_1_perp) / <b_2, b_1_perp>
    where b_perp is the vector perpendicular to b.

    For n-D, we solve B^T X = I.

    Returns:
        List of dual basis vectors.
    """
    n = len(basis)
    if n == 2:
        return _dual_basis_2d(basis)
    return _dual_basis_nd(basis)


def _dual_basis_2d(basis: List[List[float]]) -> List[List[float]]:
    """Compute dual basis for 2D using explicit perpendicular formula."""
    b1, b2 = basis[0], basis[1]
    # Perpendicular to b1: rotate 90 degrees
    b1_perp = [-b1[1], b1[0]]
    b2_perp = [-b2[1], b2[0]]

    det = vec_dot(b1, b2_perp)  # = b1[0]*b2[1] - b1[1]*b2[0]
    if abs(det) < 1e-15:
        raise ValueError("Basis vectors are linearly dependent")

    # b^1 is perpendicular to b2, scaled so <b1, b^1> = 1
    b1_star = [b2_perp[0] / det, b2_perp[1] / det]
    # b^2 is perpendicular to b1, scaled so <b2, b^2> = 1
    b2_star = [-b1_perp[0] / det, -b1_perp[1] / det]

    return [b1_star, b2_star]


def _dual_basis_nd(basis: List[List[float]]) -> List[List[float]]:
    """
    Compute dual basis for n-D by solving B^T X = I.
    Uses Gaussian elimination.
    """
    n = len(basis)
    # Build augmented matrix [B^T | I]
    aug = []
    for i in range(n):
        row = [basis[j][i] for j in range(n)]  # i-th row of B^T = i-th column of B
        row += [1.0 if j == i else 0.0 for j in range(n)]
        aug.append(row)

    # Gaussian elimination
    for col in range(n):
        # Find pivot
        max_row = col
        for row in range(col + 1, n):
            if abs(aug[row][col]) > abs(aug[max_row][col]):
                max_row = row
        aug[col], aug[max_row] = aug[max_row], aug[col]

        pivot = aug[col][col]
        if abs(pivot) < 1e-15:
            raise ValueError("Basis is singular (linearly dependent vectors)")

        # Scale pivot row
        for j in range(2 * n):
            aug[col][j] /= pivot

        # Eliminate
        for row in range(n):
            if row != col:
                factor = aug[row][col]
                for j in range(2 * n):
                    aug[row][j] -= factor * aug[col][j]

    # Extract dual basis from right half
    dual = []
    for i in range(n):
        dual.append([aug[i][n + j] for j in range(n)])

    return dual


# ---------------------------------------------------------------------------
# 6. Approximate SVP using Gram-Schmidt lower bound
# ---------------------------------------------------------------------------

def lattice_svp_approx(basis: List[List[float]]) -> Tuple[float, Optional[List[float]], float]:
    """
    Approximate Shortest Vector Problem using Gram-Schmidt lower bound.

    Uses the lower bound OPT >= min_i |b*_i| and attempts to find a short
    vector by examining the basis vectors and their Gram-Schmidt components.

    Vazirani Section 27.4-27.5: The Gram-Schmidt vectors give a lower bound
    on OPT.  By examining individual basis vectors and their projections,
    we can obtain a rough approximation.

    Returns:
        Tuple of (shortest_length, shortest_vector, lower_bound) where:
        - shortest_length is the length of the shortest vector found
        - shortest_vector is the vector (or None)
        - lower_bound is the Gram-Schmidt lower bound on OPT
    """
    n = len(basis)
    ortho, mu = gram_schmidt(basis)
    lb = lower_bound_svp(basis)

    # Try individual basis vectors
    best_vec = None
    best_len = float('inf')

    for i in range(n):
        v = list(basis[i])
        l = vec_norm(v)
        if l > 1e-15 and l < best_len:
            best_len = l
            best_vec = v

    # Try integer combinations of pairs (small coefficients)
    for i in range(n):
        for j in range(i + 1, n):
            for ci in range(-3, 4):
                for cj in range(-3, 4):
                    if ci == 0 and cj == 0:
                        continue
                    v = vec_add(vec_scale(basis[i], ci), vec_scale(basis[j], cj))
                    l = vec_norm(v)
                    if l > 1e-15 and l < best_len:
                        best_len = l
                        best_vec = list(v)

    # Try small combinations of all basis vectors
    for mask in range(1, 1 << n):
        v = [0.0] * n
        for k in range(n):
            if mask & (1 << k):
                v = vec_add(v, basis[k])
        l = vec_norm(v)
        if l > 1e-15 and l < best_len:
            best_len = l
            best_vec = list(v)

    return best_len, best_vec, lb


# ---------------------------------------------------------------------------
# 7. Simple basis reduction (n-dimensional)
# ---------------------------------------------------------------------------

def lattice_basis_reduction(basis: List[List[float]], max_iter: int = 1000) -> List[List[float]]:
    """
    Simple basis reduction using Gram-Schmidt-guided operations.

    Attempts to reduce the basis by:
    1. Sorting basis vectors by norm
    2. Subtracting integer multiples of shorter vectors from longer ones
    3. Re-orthogonalizing and repeating

    This is a simplified version of what LLL achieves; for a full
    polynomial-time reduction algorithm, see LLL.

    Vazirani Section 27.7: The LLL algorithm achieves a reduced basis
    where the Gram-Schmidt orthogonality defect is bounded.

    Returns:
        Reduced basis as a list of vectors.
    """
    n = len(basis)
    reduced = [list(v) for v in basis]

    for _ in range(max_iter):
        changed = False

        # Sort by norm
        norms = [(vec_norm(reduced[i]), i) for i in range(n)]
        norms.sort()
        order = [idx for _, idx in norms]
        reduced = [reduced[idx] for idx in order]

        # For each pair, try to reduce the longer by the shorter
        for i in range(n):
            for j in range(i + 1, n):
                dot_jj = vec_dot(reduced[j], reduced[j])
                if dot_jj < 1e-15:
                    continue
                coeff = vec_dot(reduced[i], reduced[j]) / dot_jj
                rounded = round(coeff)
                if rounded != 0:
                    reduced[i] = vec_sub(reduced[i], vec_scale(reduced[j], rounded))
                    changed = True

        if not changed:
            break

    return reduced


# ---------------------------------------------------------------------------
# 8. LLL-style reduction (simplified)
# ---------------------------------------------------------------------------

def lll_reduce(basis: List[List[float]], delta: float = 0.75) -> List[List[float]]:
    """
    Simplified LLL lattice basis reduction.

    Implements the core LLL loop:
    1. Compute Gram-Schmidt orthogonalization
    2. For each i, perform size reduction: subtract round(mu_{i,j}) * b*_j from b_i
    3. If the Lovasz condition |b*_i|^2 >= (delta - mu_{i,i-1}^2) |b*_{i-1}|^2 fails,
       swap b_i and b_{i-1} and backtrack.

    Vazirani Section 27.7: LLL produces a reduced basis where
    |b_1| <= 2^{(n-1)/2} * OPT (approximate SVP with exponential approximation factor).

    Args:
        basis: list of n vectors in R^n
        delta: LLL parameter, must be in (1/4, 1]. Default 3/4.

    Returns:
        LLL-reduced basis.
    """
    n = len(basis)
    b = [list(v) for v in basis]
    ortho, mu = gram_schmidt(b)

    i = 1  # 1-indexed in LLL convention
    while i < n:
        # Size reduction for b[i] using b[j] for j < i
        for j in range(i - 1, -1, -1):
            coeff = round(mu[i][j])
            if coeff != 0:
                b[i] = vec_sub(b[i], vec_scale(b[j], coeff))
                # Recompute Gram-Schmidt
                ortho, mu = gram_schmidt(b)

        # Lovasz condition
        norm_i = vec_dot(ortho[i], ortho[i])
        norm_im1 = vec_dot(ortho[i - 1], ortho[i - 1])
        mu_i_im1 = mu[i][i - 1]

        if norm_i >= (delta - mu_i_im1 ** 2) * norm_im1:
            i += 1
        else:
            # Swap b[i] and b[i-1]
            b[i], b[i - 1] = b[i - 1], b[i]
            ortho, mu = gram_schmidt(b)
            i = max(i - 1, 1)

    return b


# ---------------------------------------------------------------------------
# 9. Demo function
# ---------------------------------------------------------------------------

def demo_shortest_vector() -> None:
    """
    Demonstrate shortest vector algorithms on various lattices.
    """
    print("=" * 70)
    print("Chapter 27: Shortest Vector in a Lattice")
    print("=" * 70)

    # --- 1D lattice: Euclid's algorithm ---
    print("\n--- 1. Euclid's GCD (1D lattice) ---")
    a, b = 48, 18
    print(f"  Lattice generated by {a} and {b}")
    print(f"  GCD({a}, {b}) = {euclid_gcd(a, b)}")
    print(f"  Shortest vector length = {euclid_gcd(a, b)}")
    print(f"  Euclid's algorithm: {a} = {b}*{a//b} + {a%b}")
    print(f"  Step 2: GCD({b}, {a%b}) = GCD({18}, {12})")
    print(f"  Step 3: GCD({12}, {6}) = {euclid_gcd(48, 18)}")

    # --- 2D lattice: Gauss' algorithm ---
    print("\n--- 2. Gauss' 2D Algorithm ---")
    b1 = [1.0, 1.0]
    b2 = [1.0, -1.0]
    print(f"  Basis: b1 = {b1}, b2 = {b2}")
    shortest = gauss_2d(b1, b2)
    print(f"  Shortest vector: {shortest}, length = {vec_norm(shortest):.4f}")

    b1 = [3.0, 1.0]
    b2 = [1.0, 2.0]
    print(f"\n  Basis: b1 = {b1}, b2 = {b2}")
    shortest = gauss_2d(b1, b2)
    print(f"  Shortest vector: {shortest}, length = {vec_norm(shortest):.4f}")

    # --- 3D lattice: Gauss' algorithm doesn't apply, use reduction ---
    print("\n--- 3. 3D Lattice ---")
    basis_3d = [
        [1.0, 0.0, 0.0],
        [0.5, 1.0, 0.0],
        [0.25, 0.5, 1.0],
    ]
    print(f"  Basis: {basis_3d}")
    ortho, mu = gram_schmidt(basis_3d)
    print(f"  Gram-Schmidt orthogonal vectors:")
    for i, v in enumerate(ortho):
        print(f"    b*_{i+1} = [{v[0]:.4f}, {v[1]:.4f}, {v[2]:.4f}], "
              f"norm = {vec_norm(v):.4f}")
    print(f"  Orthogonality defect: {orthogonality_defect(basis_3d):.4f}")
    print(f"  Lower bound on OPT: {lower_bound_svp(basis_3d):.4f}")

    # --- 4. Approximate SVP ---
    print("\n--- 4. Approximate SVP (Gram-Schmidt lower bound) ---")
    basis_approx = [
        [2.0, 1.0, 0.0],
        [1.0, 3.0, 1.0],
        [0.0, 1.0, 2.0],
    ]
    print(f"  Basis: {basis_approx}")
    short_len, short_vec, lb = lattice_svp_approx(basis_approx)
    print(f"  Approximate shortest vector: {short_vec}")
    print(f"  Its length: {short_len:.4f}")
    print(f"  Gram-Schmidt lower bound: {lb:.4f}")
    print(f"  Approximation ratio: {short_len / lb:.2f}x")

    # --- 5. Basis reduction ---
    print("\n--- 5. Basis Reduction ---")
    basis_reduce = [
        [1.0, 1.0, 1.0],
        [0.0, 1.0, 1.0],
        [0.0, 0.0, 1.0],
    ]
    print(f"  Original basis: {basis_reduce}")
    print(f"  Original norms: {[vec_norm(v) for v in basis_reduce]}")
    print(f"  Original orthogonality defect: {orthogonality_defect(basis_reduce):.4f}")

    reduced = lattice_basis_reduction(basis_reduce)
    print(f"  Reduced basis: {reduced}")
    print(f"  Reduced norms: {[vec_norm(v) for v in reduced]}")
    print(f"  Reduced orthogonality defect: {orthogonality_defect(reduced):.4f}")

    # --- 6. LLL Reduction ---
    print("\n--- 6. LLL Reduction ---")
    basis_lll = [
        [1.0, 1.0, 1.0],
        [0.0, 1.0, 1.0],
        [0.0, 0.0, 1.0],
    ]
    print(f"  Original basis: {basis_lll}")
    lll_reduced = lll_reduce(basis_lll)
    print(f"  LLL-reduced basis: {lll_reduced}")
    print(f"  LLL norms: {[vec_norm(v) for v in lll_reduced]}")
    print(f"  LLL orthogonality defect: {orthogonality_defect(lll_reduced):.4f}")

    # --- 7. Dual lattice ---
    print("\n--- 7. Dual Lattice ---")
    basis_dual = [
        [2.0, 1.0],
        [1.0, 1.0],
    ]
    print(f"  Original basis: {basis_dual}")
    dual = dual_basis(basis_dual)
    print(f"  Dual basis: {dual}")
    # Verify duality: <b_i, b^j> = delta_{i,j}
    for i in range(2):
        for j in range(2):
            val = vec_dot(basis_dual[i], dual[j])
            expected = 1.0 if i == j else 0.0
            print(f"    <b_{i+1}, b^{j+1}> = {val:.6f} (expected {expected})")

    # --- 8. Larger lattice example ---
    print("\n--- 8. Larger Lattice (4D) ---")
    import random
    random.seed(42)
    n = 4
    basis_large = []
    for i in range(n):
        row = [random.uniform(-1.0, 1.0) for _ in range(n)]
        # Make it somewhat well-conditioned
        row[i] += 3.0
        basis_large.append(row)

    print(f"  Random 4D basis:")
    for i, v in enumerate(basis_large):
        print(f"    b_{i+1} = [{', '.join(f'{x:.3f}' for x in v)}]")

    print(f"\n  Orthogonality defect: {orthogonality_defect(basis_large):.4f}")
    lb = lower_bound_svp(basis_large)
    print(f"  Lower bound on OPT: {lb:.4f}")

    reduced_large = lattice_basis_reduction(basis_large)
    print(f"\n  Reduced basis:")
    for i, v in enumerate(reduced_large):
        print(f"    r_{i+1} = [{', '.join(f'{x:.3f}' for x in v)}]  "
              f"(norm = {vec_norm(v):.3f})")
    print(f"  Reduced orthogonality defect: {orthogonality_defect(reduced_large):.4f}")

    print("\n" + "=" * 70)
    print("Key takeaways:")
    print("  - Euclid's algorithm finds shortest vector in 1D lattices")
    print("  - Gauss' algorithm finds shortest vector in 2D lattices")
    print("  - Gram-Schmidt gives a lower bound on OPT for any dimension")
    print("  - Basis reduction (simple or LLL) finds shorter vectors")
    print("  - LLL achieves polynomial-time approximate SVP (exponential approx)")
    print("=" * 70)


if __name__ == "__main__":
    demo_shortest_vector()
